trigger:
  - main
 
variables:
  azureServiceConnectionId: "a08b4ecc-aa03-4056-8d11-66deb4c26b54"
  webAppName: "E-commSemanticSearch"
  pythonVersion: "3.11"
 
stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    pool:
      name: selfhosted-pool   # Self-hosted pool
    steps:
    - script: |
        echo Python Version
        python --version
      displayName: "Check Python"
 
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: "Install Dependencies"
 
    - task: ArchiveFiles@2
      displayName: "Archive Files"
      inputs:
        rootFolderOrFile: "."
        includeRootFolder: false
        archiveType: zip
        archiveFile: "$(Build.ArtifactStagingDirectory)/app.zip"
        replaceExistingArchive: true
 
    - publish: "$(Build.ArtifactStagingDirectory)/app.zip"
      artifact: drop
 
- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      name: selfhosted-pool   # Self-hosted pool again
    environment: E-commSemanticSearch
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: "Deploy to Azure Web App"
            inputs:
              azureSubscription: "$(azureServiceConnectionId)"
              appType: webAppLinux
              appName: "$(webAppName)"
              package: "$(Pipeline.Workspace)/drop/app.zip"